from django.core.management.base import BaseCommand

from helpcenter.models import Lexique

class Command(BaseCommand):
    help = 'create dummy data to initialize fanfiction'
    # http://fictions-project.kanak.fr/t6-lexique-de-la-fanfiction

    def handle(self, *args, **options):
        lexiques = Lexique.objects.filter(title="Fanfiction")
        if not lexiques.exists():
            Lexique.objects.bulk_create(
                [Lexique(title="Fanfiction", definition="Littéralement « fiction écrite par un fan », la fanfiction est une histoire écrite en s'appuyant sur un univers existant. Livre, film, série télévisée, tout peut servir de médium de départ.\nLe plus souvent, elles sont postées sur Internet, sur des sites de publications, des blogs ou dans des forums, chapitre par chapitre. Ceux qui les lisent sont invités à laisser des commentaires (reviews) concernant chaque chapitre.\n\nLes fanfictions concernant des personnes réelles – acteurs/actrices, chanteurs/chanteuses, groupes de musiques et personnalités plus ou moins médiatiques en général – sont également nommées RPF (« Real People Fiction ») ou star-fics. Elles sont parfois mal vues par le reste de la communauté fanfictionnelle."),
                Lexique(title="Métafanfiction", definition="La métafanfiction est une fanfiction dans laquelle les personnages sont conscients de faire partie d'un monde fictif. Ils peuvent alors s'adresser à l'auteur, que ce soit celui de l’œuvre originale ou de la fanfiction."),
                Lexique(title="Disclaimer", definition="Le « disclaimer » – de « to disclaim » en anglais, qui signifie « nier » – est une déclaration de non-droit concernant l’œuvre sur laquelle s'appuie la fanfiction que l'on écrit.\n\nLa fanfiction étant une violation des droits d'auteurs, et donc officiellement illégale, il est important de préciser avant chaque chapitre ou avant le tout début de la publication que l’œuvre sur laquelle on s'appuie et tous ses aspects ne nous appartiennent pas. De cette façon, on renonce à toucher de l'argent avec la fiction que l'on écrit et la pratique devient légalement acceptable.\n\nDans le cadre d'une RPF/star-fic, c'est concernant les personnes réelles mises en scène que l'on fait cette déclaration. En effet, la déformation des personnalités, des événements et des paroles des stars sur lesquelles ont écrit peut s'apparenter à de la diffamation. C'est une atteinte aux droits d'image et lois apparentées.\n\nLe disclaimer d'une RPF/star-fic se doit donc de bien mentionner que les stars mises en scène et/ou citées ainsi que toutes les facettes de leur vie publique comme privée (des informations récoltées sur elles et leurs proches pour rendre leur vie avec plus de précision aux différents aspects de leur travail (citation d'interview, de paroles de chansons, etc.)) ne nous appartiennent pas, que ce que nous en faisons n'est que pure interprétation et que nous ne cherchons en rien à leur porter atteinte. "),
                Lexique(title="Fandom", definition="Le fandom (compression de « fanfic domain ») désigne la communauté des fans d'une œuvre (ou d'une star) et les activités en découlant.\n\nPour exemple, la Potter fiction est un des produits du fandom Harry Potter."),
                Lexique(title="Rating", definition="Apparenté au Pegi que l'on trouve sur les jeux vidéos, les DVDs et maintenant en avertissement visuel et sonore avant certaines publicités, annonçant clairement un avertissement concernant l'âge conseillé pour jouer au jeu et regarder le film ou la publicité, le rating est un système d'avertissement permettant de suggérer la teneur d'une fiction.\n\nLes valeurs des ratings changent en fonction des sites, mais généralement ce sont les mêmes. Le plus souvent précisés dans les règles des sites de publication, il est bon de consulter cette réglementation avant de se lancer dans l'écriture d'une fiction mais surtout dans sa publication sur le site. En effet, certains n'accepte pas tout, renseignez-vous avant de poster."),
                Lexique(title="Review", definition="Une review est un commentaire laissé par un lecteur pendant ou après sa lecture. On peut ordinairement commenter chaque chapitre individuellement.\n\nSupposé être constructif, il l'est toutefois rarement. Pour autant, c'est un encouragement toujours bienvenu pour l'auteur, qui attend souvent de savoir si sa fiction plaît avant de poster la suite (ou de l'écrire).\n\nAttention cependant, une review est un commentaire, chacun ayant le droit à la parole, il peut être dépréciateur. Généralement posté sans agressivité, il n'est pas à prendre personnellement. Il peut au contraire permettre une remise en question toujours bienvenue."),
                Lexique(title="Flame", definition="Le flame (« flamme », en français) est un commentaire agressif faisant généralement état d'un sujet qui a choqué le lecteur, qu'il s'agisse d'un sujet vraiment limite abordé dans la fiction, d'un manque de warning (rating, entre autre) ayant entraîner une lecture indésirable, ou d'un manque de soin de l'auteur amenant un certain agacement (généralement une mauvaise orthographe).\n\nIl arrive que cette agressivité soit gratuite. Il est alors déconseillé d'y répondre tout de suite pour ne pas envenimer les choses."),
                Lexique(title="Canon", definition="Le canon est l’œuvre original. Être conforme au canon, c'est suivre les éléments de l'histoire d'origine. Par définition, un UA (cf 'UA/AU') sort du canon."),
                Lexique(title="Fanon", definition="Le fanon est un mot-valise qui signifie littéralement « canon des fans ».\n\nC'est un ensemble de déductions et de suppositions des fans sur les différents aspects de l’œuvre originale qu'ils considèrent comme exactes, bien qu'elles ne soient pas clairement établies (voire pas du tout) par l’œuvre source et puissent être totalement fausses.\n\nPlus généralement, ce sont des éléments n'appartenant pas au canon de l’œuvre originale qui ont été si souvent répétés au fil des fanfictions qu'ils sont considérés comme faisant partie de l’œuvre d'origine par les fans.\n\nIl peut être posé en préfixe pour signifier qu'on ne parle pas du personnage définit par l’œuvre originale mais bien de celui recréer par les fans ou une partie des fans.\n\nDans le fandom Harry Potter, par exemple, le fanon de Draco Malfoy donne un personnage torturé en quête de rédemption, ce qui ne s'avère qu'à la lecture du Prince de Sang-Mêlé. Avant la parution du livre, cette version de Draco était donc un fanon."),
                Lexique(title="Spoiler", definition="Le spoiler vient de « to spoil », « gâcher » en anglais.\n\nUne fanfiction qui annonce un spoiler prévient donc qu'elle contient des références à des événements de l'histoire originale se produisant après ce que la parution officielle du pays permet de connaître et qu'elle risque donc de gâcher l'effet de surprise au lecteur.\n\nPour exemple, la parution du manga Naruto est plus avancée au Japon qu'en France. Ceux qui lisent des fanfictions sur Naruto mais ne lisent ni le japonais ni les scans traduits sur Internet ne peuvent donc pas savoir ce qui se passe dans la suite, pourtant déjà parue au Japon.\n\nAinsi, ceux qui lisent le japonais ou suivent la parution des scans traduits de la série savent ce qui se passera dans le manga avant ceux qui attendent la parution officielle. Si la fanfiction fait état de ces événements, elle doit prévenir dans l'en-tête qu'elle contient des spoilers, donc des aperçus du futur officiel du manga."),
                Lexique(title="Warning", definition="« Avertissement » en français, le warning donne des indications sur le contenu de la fanfiction dans le cas où l'un des sujets pourrait choquer le lecteur ou ne pas correspondre à sa tranche d'âge.\n\nIl est recommandé (impératif sur certains sites) de signaler de futures scènes de violence et/ou de sexe (suggérées ou explicites) ainsi que la mise en situation de relations homosexuelles.\n\nD'autres critères, le plus souvent préventif et humoristique, sont présent dans les avertissements, tel que la présence d'une Mary Sue/d'un Gary Stu, l'état d'esprit particulier de l'auteur au moment de l'écriture, etc."),
                Lexique(title="POV", definition="De l'anglais « point of view », POV signifie « point de vue » et se retrouve parfois écrit « PdV ».\n\nCela désigne le personnage qui raconte, donnant son point de vue, ses impressions sur les événements.\n\nLors d'un POV, on ne peut connaître que le point de vue du personnage, pas celui des autres.\n\nIl est bon de signaler la fin d'un POV avant le retour à un point de vue omniscient ou le passage au point de vue d'un autre personnage."),
                Lexique(title="Cliffanger", definition="Le cliffanger désigne la manière de finir un chapitre en coupant l'action à un moment crucial, préservant ainsi le suspense sur la suite.\n\nC'est un bon procédé pour tenir le lecteur tout au long de l'histoire. C'est un moyen sûr de savoir que vos lecteurs liront le chapitre suivant."),
                Lexique(title="Préquel", definition="Un préquel est une histoire qui raconte des événements sensées s'être passés avant le début de l'histoire officielle ou d'une de vos précédentes fanfictions.\n\nElle apporte généralement des éclaircissements sur le comportement des personnages, la nature de certains faits et permet au lecteur de mieux comprendre l'histoire de base."),
                Lexique(title="Séquel", definition="Un séquel est la suite qu'on apporte à l'histoire originale après sa fin officielle.\n\nCela peut commencer directement à la suite du dernier chapitre ou se passer des années plus tard."),
                Lexique(title="Bunny", definition="Le bunny, ou plotbunny, est une idée obsédante que vous ressentez le besoin de mettre par écrit."),
                Lexique(title="Round Robin", definition="Une round robin est une fanfiction écrite à plusieurs dans le sens où les scènes sont écrites indépendamment les une des autres.\n\nL'auteur A écrit la scène 1, l'auteur B écrit la scène 2 et ainsi de suite, chacun reprenant là où l'autre s'est arrêté.\n\nCe procédé peut être amusant pour les auteurs mais manquer de cohérence pour le lecteur."),
                Lexique(title="Flash-Back", definition="Un flash-back est un retour en arrière, dans les souvenirs du ou des personnages.\n\nIl est fréquemment utilisé pour expliquer une situation dans le présent de la fiction."),
                Lexique(title="Bêta-lecteur", definition="Le bêta-lecteur (qui n'est pas un correcteur) lit et aide à la correction des fictions à la demande des auteurs afin de les aider à les améliorer. Il se concentre essentiellement sur le fond du texte (intrigue, personnages, contexte, décors, etc.).\n\nIl fait attention aux détails de l'histoire, pointe les non-sens scénaristiques, contextuels et temporels, les oublis et les défauts de l'histoire et des personnages.\n\nIl peut également faire, à la demande de l'auteur, des propositions scénaristiques et contextuelles.\n\nIl ne donne pas son avis et n'a que faire de la forme du texte. "),
                Lexique(title="Correcteur", definition="Le correcteur corrige la forme d'un texte (orthographe, grammaire, conjugaison, syntaxe). C'est un précieux atout pour les auteurs rencontrant des difficultés sur les différents aspects de la langue.\n\nLe correcteur ne donne pas son avis sur le texte, ne s'occupe en rien du fond du texte. Son travail consiste uniquement à corriger la forme. Il n'est pour autant pas autorisé à changer les phrases de l'auteur."),
                Lexique(title="Critique", definition="Le critique rédige et poste des critiques sur les fictions qu'il lit, de sa propre initiative ou à la demande de l'auteur.\n\nIl se doit de faire une critique, qu'elle soit bonne ou mauvaise, complète et constructive.\n\nIl a, dans ce sens, le droit de s'attaquer à tous les aspects du texte qu'il critique, fond comme forme, mais sans jamais y apporter de correction – à moins que l'auteur lui-même le lui demande. S'il accepte, il se place alors pour un temps comme que bêta-lecteur et/ou correcteur, rôle(s) qu'il peut quitter à tout moment selon ses désirs."),
                Lexique(title="One-Shot", definition="Le One-Shot (abrégé OS) est une histoire en « un seul tenant ». Généralement écrite en un seul chapitre, elle se lit d'un coup et se finit avec le chapitre."),
                Lexique(title="Arc", definition="Un arc est une suite de one shots dont les courtes histoires s'inscrivent dans un même scénario et sur une même ligne temporelle.\n\nPas aussi suivit qu'une fanfiction à chapitre, l'arc met en lumière des scénettes qui, mises bout à bout, dévoilent une histoire cohérente dont on ne peut que deviner les détails, puisqu'ils ne sont pas écrits."),
                Lexique(title="Série", definition="Une série est une suite de fanfictions qui s’inscrivent dans un même univers cohérent.\n\nDifférent de l'arc par le fait qu'il est constitué de fanfictions à chapitres et non de one shots, la série emprunte cependant le même principe."),
                Lexique(title="Drabble", definition="Un drabble est un texte de 100 mots exactement (avec une tolérance de 15 mots supplémentaires pour le titre).\n\nIl existe sous forme de short-drabble, soit un texte de 50 mots, et de double-drabble, soit un texte de 200 mots."),
                Lexique(title="Vignette", definition="Une vignette est un texte court généralement composé d'une seule scène et traitant des pensées, de l'état d'esprit et/ou des sentiment d'un personnage à un moment donné ou en réaction à un événement précis."),
                Lexique(title="Ficlet", definition="Une ficlet est une fanfiction de plus de 100 mots mais de moins de 1000 mots.\n\nElle est à différencier du drabble par le fait qu'elle a un nombre de mots variable à loisir (sans dépasser les 1000 mots), alors que le drabble doit contenir 100 mots précisément (ou 50 dans un short-drabble et 200 dans un double-drabble)."),
                Lexique(title="Recueil", definition="Un recueil est, comme son nom l'indique, un recueil de fictions. Généralement des drabbles, des vignettes et/ou des ficlets, ces fictions n'ont pas forcément la même optique, le même scénario implicite ni même la même ligne temporelle mais traitent tous du même sujet. Ils ne racontent pas une histoire mais se basent sur la même œuvre."),
                Lexique(title="Song-Fic", definition="Une song fic est une fanfiction tournant autour des paroles d'une chanson existante.\n\nL'intrigue est généralement entrecoupée par les paroles de la chanson choisie."),
                Lexique(title="WIP", definition="De l'anglais « work in progress » qui se traduit par « travail en cours ».\n\nOn annote ainsi une fiction quand on commence à la poster avant d'avoir fini de l'écrire.\n\nSelon les auteurs et les situations, ça peut implicitement signifier « je commence à poster mais je ne sais pas où je vais » ou « j'ai tout dans la tête mais je commence à poster. »"),
                Lexique(title="Hiatus", definition="Issu du français (si, si !) ce mot signifie entre autre « décalage » et « coupure ».\n\nDans le domaine fanfictionnel, il désigne une fanfiction arrêtée de manière temporaire ou définitive.")]
            )
            self.stdout.write(self.style.SUCCESS('Created lexique definitions'))
