# Generated by Django 3.2.14 on 2022-08-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200223_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TU', 'Tutorial'), ('AR', 'Article'), ('IN', 'Information')], default='AR', max_length=2),
        ),
    ]
