# Generated by Django 4.2.10 on 2024-02-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id_alter_tag_id'),
        ('posts', '0003_post_category'),
    ]

    operations = [
    ]
