# Generated by Django 2.0.2 on 2018-08-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lexique',
        ),
    ]
