# Generated by Django 2.0.2 on 2018-02-23 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterModelOptions(
            name='fanfic',
            options={'ordering': ('-publish',), 'verbose_name': 'fanfic', 'verbose_name_plural': 'fanfics'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'sous-categorie', 'verbose_name_plural': 'sous-categories'},
        ),
        migrations.AddField(
            model_name='fanfic',
            name='classement',
            field=models.CharField(choices=[('g', 'G'), ('13', '13+'), ('r', 'R'), ('18', '18+')], default='g', max_length=2),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='comment',
            name='fanfic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Fanfic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
    ]
