# Generated by Django 4.2.11 on 2024-12-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_flatpages_id_alter_notification_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatPages',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
