# Generated by Django 2.0.2 on 2018-03-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180312_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
