# Generated by Django 2.0.2 on 2018-03-12 19:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180312_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RO', 'Romance'), ('SU', 'Surnaturel'), ('ER', 'Erotique'), ('DR', 'Drame'), ('AM', 'Amitié'), ('AC', 'Action-Aventure'), ('SC', 'School-Fic'), ('MY', 'Mystère'), ('GE', 'Général'), ('DCED', "De cape et d'épée"), ('LE', 'Lemon'), ('HU', 'Humour'), ('OS', 'One-Shot'), ('SU', 'Suspense'), ('TH', 'Thriller'), ('HO', 'Horreur'), ('HF', 'Heroic Fantasy'), ('TR', 'Tragédie'), ('CO', 'Cross-Over')], max_length=3),
        ),
    ]
