# Generated by Django 2.0.2 on 2018-03-17 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180317_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
