# Generated by Django 2.0.2 on 2018-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180616_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followstories',
            options={'ordering': ('-created',), 'verbose_name': 'follow story', 'verbose_name_plural': 'follow stories'},
        ),
        migrations.AlterModelOptions(
            name='followuser',
            options={'ordering': ('-created',), 'verbose_name': 'follow user', 'verbose_name_plural': 'follow users'},
        ),
        migrations.AddField(
            model_name='fanfic',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
