# Generated by Django 2.0.2 on 2018-06-18 19:00

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180616_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionsLegales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', markdownx.models.MarkdownxField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mention légale',
                'verbose_name_plural': 'mentions légales',
            },
        ),
        migrations.CreateModel(
            name='PolitiqueConfidentialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', markdownx.models.MarkdownxField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'politique de confidentialité',
                'verbose_name_plural': 'politiques de confidentialité',
            },
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
