# Generated by Django 2.0.2 on 2018-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180619_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
