# Generated by Django 2.0.2 on 2018-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_post_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
