# Generated by Django 2.0.2 on 2018-08-19 19:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_lexique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoireAuxQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('fan', 'Fanfictions'), ('sit', 'Le site')], default='fan', max_length=3)),
                ('question', models.CharField(max_length=64)),
                ('reponse', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AddField(
            model_name='fanfic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
