# Generated by Django 2.0.2 on 2018-08-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180819_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foireauxquestions',
            options={'verbose_name': 'Foire aux questions', 'verbose_name_plural': 'Foires aux questions'},
        ),
    ]
