# Generated by Django 2.0.2 on 2018-08-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_category_logic_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logic_value',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
