# Generated by Django 2.0.2 on 2018-08-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180823_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentByChapter',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Comment')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by_chapters', to='api.Chapter')),
            ],
            options={
                'verbose_name': 'comment by chapter',
                'verbose_name_plural': 'comments by chapters',
                'ordering': ('created',),
            },
            bases=('api.comment',),
        ),
    ]
