# Generated by Django 2.0.3 on 2018-10-04 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_commentbychapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
