# Generated by Django 2.0.8 on 2018-10-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_accountprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('instagram', 'Instagram')], max_length=255)),
                ('nichandle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social account',
                'verbose_name_plural': 'Social accounts',
                'ordering': ('network',),
            },
        ),
        migrations.AlterModelOptions(
            name='accountprofile',
            options={'ordering': ('user',), 'verbose_name': 'Account profile', 'verbose_name_plural': 'Accounts profiles'},
        ),
        migrations.AddField(
            model_name='social',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network', to='api.AccountProfile'),
        ),
    ]
