# Generated by Django 2.0.8 on 2018-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20181006_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], default='publié', max_length=10),
        ),
    ]
