# Generated by Django 2.0.8 on 2018-11-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_topic_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoireAuxQuestions',
        ),
        migrations.DeleteModel(
            name='Lexique',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='starter',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
