# Generated by Django 2.0.8 on 2018-11-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20181114_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
