# Generated by Django 2.0.8 on 2018-12-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_fanfic_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
