# Generated by Django 2.0.8 on 2019-02-22 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20181224_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
