export default {
    message: {
        errorFetch: 'There is a problem with the request.',
        addNewSocialNetwork: 'Add a social network',
        changePassword: 'Password change',
        network: 'Network',
        nichandle: 'Username',
        passwordChangedNotification: 'Your password will be updated.',
        socialNetworkAdded: 'Social network will be added.',
        changeProfileEdit: 'Edit profile',
        dateOfBirth: 'Date of birth',
        Photo: 'Photo',
        Biography: 'Biography',
        BiographyPlaceholder: 'About you',
        changeUserInfos: 'Edit user informations',
        profileUpdated: 'Profile will be updated.',
        email: 'Email address',
        isActive: 'Active',
        dateJoined: 'User since',
        username: 'Username',
        isStaff: 'Staff',
        infosUpdated: 'Personal informations will be updated.',
        textPublish: 'Publish',
        textDraft: 'Draft',
        textRating: 'Rating',
        textStatus: 'Status',
        textGenres: 'Genres',
        textCategory: 'Category',
        textSubcategory: 'Subcategory',
        textTitleStoy: 'Title of the story',
        removePhotoText: 'Remove photo',
        warningRemovePhoto: 'Warning! There is a no way back with this operation :-)',
        myStoriesLabel: 'My fanfictions',
        favoriteAuthorsLabel: 'Starred authors',
        favoriteStoriesLabel: 'Starred fanfictions',
        NotificationsLabel: 'My notifications',
        notConnectedLabel: 'Your are logged out.',
        vosFanfictionsLabel: 'Your fanfictions',
        emptyMessageFanfiction: 'You haven\'t got fanfictions here. Free your creativity !',
        emptyMessageStarredFanfiction: 'No favorite stories',
        emptyMessageStarredAuthors: 'No favorite authors',
        newsText: 'No news | {n} new | {n} news',
        readMoreLabel: 'Read more',
        showMore: 'Show more',
        showLess: 'Show less',
        watchLabel: 'Watch',
        messageLabel: 'Message',
        fanfictionNotFound: 'Fanfiction not found.',
        commentairesText: 'No comment | {n} comment | {n} comments',
        byChapterText: 'By chapter',
        AllCommentsText: 'All',
        answeredComments: 'Author \'s answers',
        removeAccountLabel: 'Disable an account ?',
        ecrireFanfictions: 'Write fanfictions',
        allFanfictions: 'All fanfictions',
        removeAccountText: 'After deletion, your account will be disabled and no operation can be performed. Delete account ?',
        lexiqueLabel: 'Dictionary of the fanfiction',
        faqLabel: 'Frequently Asked Questions',
        forumLabel: 'Forum of Fanfiction',
        contactLabel: 'Contact the webmaster',
        mentionsLegalesLabel: 'Legal notice',
        politiqueDeConfidentialite: 'Privacy policies',
        fermerButtonLabel: 'Close',
        formContactTitle: 'Contact form',
        formContactValidateLabel: 'Send message',
        formContactEmailLabel: 'E-mail',
        formContactSubjectLabel: 'Object',
        formContactMessageLabel: 'Message text',
        loginLabel: 'Login',
        logoutLabel: 'Logout',
        greetLabel: 'Hi',
        lireFanfictionsLabel: 'Read fanfictions',
        newsLabel: 'News',
        newsEditingLabel: 'Add / Edit news',
        aideLabel: 'Help',
        searchLabel: 'Search',
        searchLabelFanfiction: 'Search on Fanfiction...',
        publishedAtLabel: 'Published at',
        miseAJourLabel: 'Updated at',
        authorLabel: 'Author',
        UsernameOrEmailLabel: 'Username or E-mail',
        passwordLabel: 'Password',
        confirmPasswordLabel: 'Confirme password',
        registerLabel: 'Register',
        connectionLabel: 'Login',
        createNewAccountLabel: 'Create a new account',
        forgotPasswordLabel: 'Forgot Password',
        signalerLabel: 'Abuse',
        formatPDFLabel: 'Download PDF',
        descriptionLabel: 'Description',
        synopsisLabel: 'Synopsis',
        creditsLabel: 'Credits',
        recommendedFanficsLabel: 'Most viewed fanfictions',
        commentairesLabel: 'Reviews',
        inReplyToLabel: 'In reply to',
        writeCommentLabel: 'Write a comment on {n}',
        writeCommentChapterLabel: 'Write an comment on this chapter {n}',
        UsernameOrPseudoLabel: 'Name or pseudo',
        emailPlaceholderLabel: 'E-mail (only author see it)',
        donnezVotreAvisLabel: 'Suggest review',
        feedBackTextLabel: 'Only fanfictions that do not comply with the site\'s code of conduct will be deleted.',
        followAuthorText: 'Follow the autor',
        NotFollowAuthorText: 'Do not follow the author',
        followFanficText: 'Follow the story',
        NotFollowFanficText: 'Do not follow the story',
        writeStoryLabel: 'Story description',
        createStoryLabel: 'Submit new story',
        selectLabel: 'Select',
        editStoryLabel: 'Edit story',
        removeStoryLabel: 'Delete story',
        chapterLabel: 'Chapters',
        contentLabel: 'Content',
        addChapterLabel: 'Add a chapter',
        editChapterTitle: 'Edit chapter',
        removeChapterTitle: 'Delete chapter {a} id #{n}',
        removeStoryDisclaimerText: 'Are you sure to delete this story "{a}" id# {n} ?',
        textTitleChapter: 'Chapter title',
        connexionUser: 'Logged as <b>{0}</b>',
    }
}
