export default {
    message: {
        errorFetch: 'There is a problem with the request.',
        addNewSocialNetwork: 'Add a social network',
        changePassword: 'Password change',
        network: 'Network',
        nichandle: 'Username',
        passwordChangedNotification: 'Your password will be updated.',
        socialNetworkAdded: 'Social network will be added.',
        changeProfileEdit: 'Edit profile',
        dateOfBirth: 'Date of birth',
        Photo: 'Photo',
        Biography: 'Biography',
        BiographyPlaceholder: 'About you',
        changeUserInfos: 'Edit user informations',
        profileUpdated: 'Profile will be updated.',
        email: 'Email address',
        isActive: 'Active',
        dateJoined: 'User since',
        username: 'Username',
        isStaff: 'Staff',
        infosUpdated: 'Personal informations will be updated.',
        textPublish: 'Publish',
        textDraft: 'Draft',
        textRating: 'Rating',
        textStatus: 'Status',
        textGenres: 'Genres',
        textCategory: 'Category',
        textSubcategory: 'Subcategory',
        textTitleStoy: 'Title of the story',
        removePhotoText: 'Remove photo',
        warningRemovePhoto: 'Warning! There is a no way back with this operation :-)',
        myStoriesLabel: 'My fanfictions',
        favoriteAuthorsLabel: 'Starred authors',
        favoriteStoriesLabel: 'Starred fanfictions',
        NotificationsLabel: 'My notifications',
        notConnectedLabel: 'Your are logged out.',
        vosFanfictionsLabel: 'Your fanfictions',
        emptyMessageFanfiction: 'You haven\'t got fanfictions here. Free your creativity !',
        newsLabel: 'No news | {n} new | {n} news',
        readMoreLabel: 'Read more',
        showMore: 'Show more',
        showLess: 'Show less',
        watchLabel: 'Watch',
        messageLabel: 'Message',
        fanfictionNotFound: 'Fanfiction not found.',
        commentairesText: 'No comment | {n} comment | {n} comments',
        byChapterText: 'By chapter',
        AllCommentsText: 'All',
        answeredComments: 'Author \'s answers',
        removeAccountLabel: 'Disable an account ?',
        ecrireFanfictions: 'Write fanfictions',
        allFanfictions: 'All fanfictions',
        removeAccountText: 'After deletion, your account will be disabled and no operation can be performed. Delete account ?',
        lexiqueLabel: 'Dictionary of the fanfiction',
        faqLabel: 'Frequently Asked Questions',
        forumLabel: 'Forum of Fanfiction',
        contactLabel: 'Contact the webmaster'
    }
}
