export default {
    message: {
        errorFetch: 'Il y a un problème avec la requète.',
        addNewSocialNetwork: 'Ajouter un réseau social',
        changePassword: 'Changer le mot de passe',
        network: 'Réseau social',
        nichandle: 'Identifiant',
        passwordChangedNotification: 'Votre mot de passe va être changer.',
        socialNetworkAdded: 'Réseau social va être ajouter.',
        changeProfileEdit: 'Modifier votre profil',
        dateOfBirth: 'Date de naissance',
        Photo: 'Photo',
        Biography: 'Biographie',
        BiographyPlaceholder: 'Quelques mots sur vous...',
        changeUserInfos: 'Modifer vos informations personnelles',
        profileUpdated: 'Votre profil va être mis à jour.',
        email: 'Adresse e-mail',
        isActive: 'Actif',
        dateJoined: 'Utilisateur depuis le',
        username: 'Pseudo',
        isStaff: 'Staff',
        infosUpdated: 'Les infos vont être mise à jour.',
        textPublish: 'Publié',
        textDraft: 'Brouillon',
        textRating: 'Classement',
        textStatus: 'Status',
        textGenres: 'Genres',
        textCategory: 'Categorie',
        textSubcategory: 'Subcategorie',
        textTitleStoy: 'Titre de l\'histoire',
        removePhotoText: 'Supprimer la photo',
        warningRemovePhoto: 'Attention! Cette opération est non réversible :-)',
        myStoriesLabel: 'Mes fanfictions',
        favoriteAuthorsLabel: 'Auteurs favoris',
        favoriteStoriesLabel: 'Fanfictions favorites',
        NotificationsLabel: 'Mes notifications',
        notConnectedLabel: 'Vous n\'êtes pas authentifier.',
        vosFanfictionsLabel: 'Vos fanfictions',
        emptyMessageFanfiction: 'Vous n\'avez pas encore de fanfictions. Libérer votre créativité !',
        newsLabel: 'Aucunes actualités | {n} actualité | {n} actualités',
        readMoreLabel: 'En savoir plus',
        showMore: 'Voir plus',
        showLess: 'Voir moins',
        watchLabel: 'Voir',
        messageLabel: 'Message',
        fanfictionNotFound: 'Fanfiction non trouvée.',
        commentairesText: 'Aucun commentaire | {n} commentaire | {n} commentaires',
        byChapterText: 'Par chapitre',
        AllCommentsText: 'Tous',
        answeredComments: 'Réponses de l\'auteur',
        connexionUser: 'Vous êtes connecter en tant que {0}',
        ecrireFanfictions: 'Ecrire une fanfiction',
        removeAccountLabel: 'Supprimer le compte',
        removeAccountText: 'Après la suppression, votre compte sera désactivé et aucune opération ne pourra être effectuer. Supprimer le compte ?',
        allFanfictions: 'Toutes les fanfictions',
        lexiqueLabel: 'Dico de la fanfiction',
        faqLabel: 'Foire aux questions',
        forumLabel: 'Forum de Fanfiction',
        contactLabel: 'Contacter le webmestre'
    }
}
