export default {
    message: {
        errorFetch: 'Il y a un problème avec la requète.',
        addNewSocialNetwork: 'Ajouter un réseau social',
        changePassword: 'Changer le mot de passe',
        network: 'Réseau social',
        nichandle: 'Identifiant',
        passwordChangedNotification: 'Votre mot de passe va être changer.',
        socialNetworkAdded: 'Réseau social va être ajouter.',
        changeProfileEdit: 'Modifier votre profil',
        dateOfBirth: 'Date de naissance',
        Photo: 'Photo',
        Biography: 'Biographie',
        BiographyPlaceholder: 'Quelques mots sur vous...',
        changeUserInfos: 'Modifer vos informations personnelles',
        profileUpdated: 'Votre profil va être mis à jour.',
        email: 'Adresse e-mail',
        isActive: 'Actif',
        dateJoined: 'Utilisateur depuis le',
        username: 'Pseudo',
        isStaff: 'Staff',
        infosUpdated: 'Les infos vont être mise à jour.',
        textPublish: 'Publié',
        textDraft: 'Brouillon',
        textRating: 'Classement',
        textStatus: 'Status',
        textGenres: 'Genres',
        textCategory: 'Categorie',
        textSubcategory: 'Subcategorie',
        textTitleStoy: 'Titre de l\'histoire',
        textTitleChapter: 'Titre du chapitre',
        removePhotoText: 'Supprimer la photo',
        warningRemovePhoto: 'Attention! Cette opération est non réversible :-)',
        myStoriesLabel: 'Mes fanfictions',
        favoriteAuthorsLabel: 'Auteurs favoris',
        favoriteStoriesLabel: 'Fanfictions favorites',
        NotificationsLabel: 'Mes notifications',
        notConnectedLabel: 'Vous n\'êtes pas authentifier.',
        vosFanfictionsLabel: 'Mes fanfictions',
        emptyMessageFanfiction: 'Vous n\'avez pas encore de fanfictions. Libérer votre créativité !',
        emptyMessageStarredFanfiction: 'Pas d\'histoires favorites',
        emptyMessageStarredAuthors: 'Pas d\'auteurs favoris',
        newsText: 'Aucunes actualités | {n} actualité | {n} actualités',
        readMoreLabel: 'En savoir plus',
        showMore: 'plus',
        showLess: 'moins',
        watchLabel: 'Voir',
        messageLabel: 'Message',
        fanfictionNotFound: 'Fanfiction non trouvée.',
        commentairesText: 'Aucun commentaire | {n} commentaire | {n} commentaires',
        byChapterText: 'Par chapitre',
        AllCommentsText: 'Tous',
        answeredComments: 'Réponses de l\'auteur',
        connexionUser: 'Vous êtes connecter en tant que <b>{0}</b>',
        ecrireFanfictions: 'Ecrire une fanfiction',
        removeAccountLabel: 'Supprimer le compte',
        removeAccountText: 'Après la suppression, votre compte sera désactivé et aucune opération ne pourra être effectuer. Supprimer le compte ?',
        allFanfictions: 'Toutes les fanfictions',
        lexiqueLabel: 'Dico de la fanfiction',
        faqLabel: 'Foire aux questions',
        forumLabel: 'Forum de Fanfiction',
        contactLabel: 'Contacter le webmestre',
        agreedLabel: 'J\'ai compris',
        cookieMessage: 'Ce site utilise des cookies pour vous assurer la meilleure expérience sur notre site.',
        mentionsLegalesLabel: 'Mentions légales',
        politiqueDeConfidentialite: 'Politique de confidentialité',
        fermerButtonLabel: 'Fermer',
        formContactTitle: 'Formulaire de contact',
        formContactValidateLabel: 'Envoyer le message',
        formContactEmailLabel: 'E-mail',
        formContactSubjectLabel: 'Objet',
        formContactMessageLabel: 'Texte de votre message',
        loginLabel: 'Se connecter',
        logoutLabel: 'Se déconnecter',
        greetLabel: 'Bonjour',
        lireFanfictionsLabel: 'Lire des histoires',
        newsLabel: 'Nouveautés',
        newsEditingLabel: 'Ajout / Edition actualités',
        aideLabel: 'Aide',
        searchLabel: 'Rechercher',
        searchLabelFanfiction: 'Rechercher sur Fanfiction...',
        publishedAtLabel: 'Publié le',
        miseAJourLabel: 'Mis à jour le',
        authorLabel: 'Auteur',
        UsernameOrEmailLabel: 'Username ou E-mail',
        passwordLabel: 'Mot de passe',
        actualPasswordLabel: 'Mot de passe actuel',
        newPasswordLabel: 'Nouveau mot de passe',
        confirmPasswordLabel: 'Confirmer le mot de passe',
        registerLabel: 'S\'enregister',
        connectionLabel: 'Se connecter',
        createNewAccountLabel: 'Création d\'un nouveau compte',
        forgotPasswordLabel: 'Oubli de mot de passe',
        signalerLabel: 'Signaler',
        formatPDFLabel: 'Télécharger un PDF',
        descriptionLabel: 'Description',
        synopsisLabel: 'Synopsis',
        creditsLabel: 'Credits',
        recommendedFanficsLabel: 'Fanfictions recommandées',
        commentairesLabel: 'Commentaires',
        inReplyToLabel: 'En réponse à',
        writeCommentLabel: 'Ecrire un commentaire sur {n}',
        writeCommentChapterLabel: 'Ecrire un commentaire sur le chapitre {n}',
        UsernameOrPseudoLabel: 'Nom ou pseudo',
        emailPlaceholderLabel: 'Votre e-mail (seul l\'auteur le verra)',
        donnezVotreAvisLabel: 'Donnez votre avis',
        feedBackTextLabel: 'Seuls les fanfictions ne répondant pas à la charte de bonne conduite du site seront supprimées.',
        followAuthorText: 'Suivre l\'auteur',
        NotFollowAuthorText: 'Ne plus suivre l\'auteur',
        followFanficText: 'Suivre l\'histoire',
        NotFollowFanficText: 'Ne plus suivre l\'histoire',
        writeStoryLabel: 'Description de l\'histoire',
        createStoryLabel: 'Créer une nouvelle histoire',
        selectLabel: 'Sélectionner',
        editStoryLabel: 'Editer l\'histoire',
        removeStoryLabel: 'Supprimer l\' histoire',
        chapterLabel: 'Chapitres',
        contentLabel: 'Contenu',
        addChapterLabel: 'Ajouter un chapitre à l\'histoire',
        editChapterTitle: 'Editer un chapitre',
        removeChapterTitle: 'Supprimer le chapitre {a} no. #{n}',
        removeStoryDisclaimerText: 'Etes vous certain de supprimer cette histoire "{a}" id# {n} ?',
        actionsLabel: "Actions",
        removeChapterLabel: "Supprimer"
    }
}
