# Generated by Django 2.2 on 2020-01-12 23:25

import api.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fanfics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('text', models.TextField()),
                ('order', api.fields.OrderField(blank=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], default='publié', max_length=10)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to=settings.AUTH_USER_MODEL)),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='fanfics.Fanfic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
