# Generated by Django 4.2.11 on 2024-12-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_alter_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
