# Generated by Django 4.2.11 on 2024-12-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_chapter_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], default='brouillon', max_length=10),
        ),
    ]
