# Generated by Django 5.2.9 on 2025-12-25 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_alter_chapter_published_alter_chapter_status'),
        ('fanfics', '0011_userfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='author',
            field=models.ForeignKey(help_text='Author of the chapter', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='fanfic',
            field=models.ForeignKey(help_text='Fanfic the chapter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='fanfics.fanfic'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], db_index=True, default='brouillon', max_length=10),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['fanfic', 'status'], name='chapters_ch_fanfic__041daf_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['author', 'status'], name='chapters_ch_author__271129_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['published'], name='chapters_ch_publish_bcdb88_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'fanfic'), name='unique_chapter_order_per_fanfic'),
        ),
    ]
