# Generated by Django 3.2.14 on 2022-09-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200217_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
