# Generated by Django 4.2.10 on 2024-02-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountprofile_location'),
        ('accounts', '0003_alter_accountprofile_id_alter_followstories_id_and_more'),
    ]

    operations = [
    ]
