# Generated by Django 5.2.9 on 2025-12-27 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountprofile_options_notification'),
        ('fanfics', '0011_userfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followstories',
            unique_together={('from_user', 'to_fanfic')},
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together={('user_from', 'user_to')},
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('network', 'account')},
        ),
    ]
