# Generated by Django 5.2.9 on 2025-12-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_followstories_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='reco_consent_given',
            field=models.BooleanField(default=True),
        ),
    ]
