const { gitDescribeSync } = require('git-describe');
const { writeFileSync } = require('fs');
const { resolve, relative } = require('path');


// Target the directory of the calling script
// Recommended when you want to target the repo your app resides in

// With options (see below)
const gitInfo = gitDescribeSync({
    dirtyMark: false,
    dirtySemver: false,
});

const file = resolve(__dirname, '../src/constants', 'version.ts');
writeFileSync(file, 
    `
    // this file is automatically generated by version.ts script
    /* tslint:disable */
    export const VERSION = ${JSON.stringify(gitInfo, null, 2)};
    /* tslint:enable */
`, {encoding: 'utf-8'});

console.log(`Wrote version info into ${gitInfo.semver.version} to ${relative(resolve(__dirname, '..'), file)}`);