# Generated by Django 4.2.11 on 2024-12-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0002_alter_board_id_alter_foireauxquestions_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='starter',
        ),
        migrations.AlterModelOptions(
            name='foireauxquestions',
            options={'ordering': ['libelle'], 'verbose_name': 'Foire aux questions', 'verbose_name_plural': 'Foires aux questions'},
        ),
        migrations.AlterModelOptions(
            name='lexique',
            options={'ordering': ['title'], 'verbose_name': 'Lexique', 'verbose_name_plural': 'Lexiques'},
        ),
        migrations.AlterField(
            model_name='foireauxquestions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lexique',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
