# Generated by Django 5.2.9 on 2025-12-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0003_remove_message_created_by_remove_message_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foireauxquestions',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foireauxquestions',
            name='question',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='foireauxquestions',
            index=models.Index(fields=['question'], name='helpcenter__questio_b6a801_idx'),
        ),
        migrations.AddIndex(
            model_name='lexique',
            index=models.Index(fields=['title'], name='helpcenter__title_6149f0_idx'),
        ),
    ]
