# Generated by Django 5.2.9 on 2025-12-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_id_alter_subcategory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(db_index=True, max_length=200)),
                ('logic_value', models.CharField(blank=True, default='', max_length=60)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_categories', to='categories.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_subcategories', to='categories.subcategory')),
            ],
            options={
                'ordering': ('entity',),
            },
        ),
    ]
