# Generated by Django 5.2.9 on 2025-12-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_entitycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitycategory',
            name='category',
        ),
    ]
