
    // this file is automatically generated by version.ts script
    /* tslint:disable */
    export const VERSION = {
  "dirty": true,
  "raw": "v1.4.0-70-gbc0ac1d-dirty",
  "hash": "gbc0ac1d",
  "distance": 70,
  "tag": "v1.4.0",
  "semver": {
    "options": {
      "loose": false,
      "includePrerelease": false
    },
    "loose": false,
    "raw": "v1.4.0",
    "major": 1,
    "minor": 4,
    "patch": 0,
    "prerelease": [],
    "build": [],
    "version": "1.4.0"
  },
  "suffix": "70-gbc0ac1d-dirty",
  "semverString": "1.4.0+70.gbc0ac1d"
};
    /* tslint:enable */
