
    // this file is automatically generated by version.ts script
    /* tslint:disable */
    export const VERSION = {
  "dirty": true,
  "raw": "v1.4.0-160-g8f4d70b-dirty",
  "hash": "g8f4d70b",
  "distance": 160,
  "tag": "v1.4.0",
  "semver": {
    "options": {
      "loose": false,
      "includePrerelease": false
    },
    "loose": false,
    "raw": "v1.4.0",
    "major": 1,
    "minor": 4,
    "patch": 0,
    "prerelease": [],
    "build": [],
    "version": "1.4.0"
  },
  "suffix": "160-g8f4d70b-dirty",
  "semverString": "1.4.0+160.g8f4d70b"
};
    /* tslint:enable */
