
    // this file is automatically generated by version.ts script
    /* tslint:disable */
    export const VERSION = {
  "dirty": true,
  "raw": "v1.4.0-161-gb44dd18-dirty",
  "hash": "gb44dd18",
  "distance": 161,
  "tag": "v1.4.0",
  "semver": {
    "options": {
      "loose": false,
      "includePrerelease": false
    },
    "loose": false,
    "raw": "v1.4.0",
    "major": 1,
    "minor": 4,
    "patch": 0,
    "prerelease": [],
    "build": [],
    "version": "1.4.0"
  },
  "suffix": "161-gb44dd18-dirty",
  "semverString": "1.4.0+161.gb44dd18"
};
    /* tslint:enable */
