# Generated by Django 2.2 on 2020-01-12 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RO', 'Romance'), ('SU', 'Surnaturel'), ('ER', 'Erotique'), ('DR', 'Drame'), ('AM', 'Amitié'), ('AC', 'Action-Aventure'), ('SC', 'School-Fic'), ('MY', 'Mystère'), ('GE', 'Général'), ('DCED', "De cape et d'épée"), ('LE', 'Lemon'), ('HU', 'Humour'), ('OS', 'One-Shot'), ('SUS', 'Suspense'), ('TH', 'Thriller'), ('HO', 'Horreur'), ('HF', 'Heroic Fantasy'), ('TR', 'Tragédie'), ('CO', 'Cross-Over')], default='RO', max_length=4)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Fanfic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('synopsis', models.CharField(blank=True, default='', max_length=250)),
                ('credits', models.CharField(blank=True, default='', max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('classement', models.CharField(choices=[('g', 'G'), ('13', '13+'), ('r', 'R'), ('18', '18+')], default='g', max_length=2)),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('RO', 'Romance'), ('SU', 'Surnaturel'), ('ER', 'Erotique'), ('DR', 'Drame'), ('AM', 'Amitié'), ('AC', 'Action-Aventure'), ('SC', 'School-Fic'), ('MY', 'Mystère'), ('GE', 'Général'), ('DCED', "De cape et d'épée"), ('LE', 'Lemon'), ('HU', 'Humour'), ('OS', 'One-Shot'), ('SUS', 'Suspense'), ('TH', 'Thriller'), ('HO', 'Horreur'), ('HF', 'Heroic Fantasy'), ('TR', 'Tragédie'), ('CO', 'Cross-Over')], max_length=59)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('was_featured_in_home', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], default='brouillon', max_length=10)),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0)),
                ('completed', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanfics', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.SubCategory')),
                ('users_like', models.ManyToManyField(blank=True, related_name='fanfics_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fanfic',
                'verbose_name_plural': 'fanfics',
                'ordering': ('-publish',),
            },
        ),
    ]
