# Generated by Django 2.2 on 2020-01-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.AddField(
            model_name='fanfic',
            name='fanfic_is_scraped',
            field=models.BooleanField(default=False),
        ),
    ]
