# Generated by Django 2.2 on 2020-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0002_auto_20200114_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='link_fanfic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
