# Generated by Django 2.2.13 on 2021-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0004_fanfic_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='language',
            field=models.CharField(default='fr', max_length=2),
        ),
    ]
