# Generated by Django 2.2.13 on 2021-05-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0005_fanfic_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='credits',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='link_fanfic',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
