# Generated by Django 4.2.11 on 2024-12-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0008_alter_fanfic_genres_alter_fanfic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
