# Generated by Django 5.2.9 on 2025-12-27 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0011_userfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié')], db_index=True, default='brouillon', max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='generated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'fanfiction')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-generated_at'], name='fanfics_rec_user_id_ffd948_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'created_at'], name='fanfics_use_user_id_e8f08e_idx'),
        ),
    ]
