name: scrape one piece fanfictions
on:
  schedule:
    - cron: '0 1 * * 1-7'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install all necessary packages
        run: pip install -r requirements.txt
      - name: Run the scraping script
        run: python3 fanfics/scraper.py op
      - name: Commit and push if content changed
        run: |-
          git config user.name "Bot"
          git config user.email "no-reply@bot.github-actions.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push